dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.3
  - smartcontractkit/chainlink@1.0.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.3'
      - '@chainlink=smartcontractkit/chainlink@1.0.1'
networks:
  default: development
  rinkeby:
    verify: True
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
  mainnet-fork-infura:
    verify: False
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
  development:
    verify: False
  ganache:
    verify: False
